#ifndef __CANPAGE_H_
#define __CANPAGE_H_

typedef enum {
	CANPAGE_NULL,
	CANPAGE_BUTTON10_ID = 11,
	CANPAGE_BUTTON11_ID = 12,
	CANPAGE_BUTTON12_ID = 13,
	CANPAGE_BUTTON8_ID = 9,
	CANPAGE_BUTTON16_ID = 17,
	CANPAGE_BUTTON19_ID = 20,
	CANPAGE_BUTTON17_ID = 18,
	CANPAGE_BUTTON18_ID = 19,
	CANPAGE_BUTTON21_ID = 22,
	CANPAGE_BUTTON5_ID = 6,
	CANPAGE_BUTTON6_ID = 7,
	CANPAGE_BUTTON14_ID = 15,
	CANPAGE_BUTTON15_ID = 16,
	CANPAGE_BUTTON22_ID = 23,
	CANPAGE_BUTTON7_ID = 8,
	CANPAGE_BUTTON13_ID = 14,
	CANPAGE_BUTTON20_ID = 21,
	CANPAGE_BUTTON9_ID = 10,
	CANPAGE_BUTTON1_ID = 2,
	CANPAGE_BUTTON4_ID = 4,
	CANPAGE_BUTTON2_ID = 5,
	CANPAGE_BUTTON3_ID = 3,
	CANPAGE_BUTTON0_ID = 1
} CanPage_ctrls_id_e;

void CanPage_init(void);
void CanPage_entry(void);
void CanPage_exit(void);

#endif
